function orgt(s) {
    return binl2hex(core_hx(str2binl(s), s.length * chrsz));
}
var bookConfig = {
    DownloadButtonVisible: "Hide",
    BookmarkButtonVisible: "Show",
    searchColor: "#00ffff",
    searchAlpha: 0.3,
    leastSearchChar: 0,
    CreatedBy: "sunset",
    CreatedTime: "20191018133728",
    BookTemplateName: "Fresh",
    loadingBackground: "#323232",
    searchPositionJS: "oiles/search/text_position[%d].js",
    loadingCaptionColor: "#DDDDDD",
    loadingBackground: "#1F2232",
    loadingPicture: "",
    bgBeginColor: "#222222",
    bgEndColor: "#222222",
    bgMRotation: 90,
    backGroundImgURL: "img/bg.jpg",
    backgroundPosition: "Stretch",
    backgroundOpacity: 100,
    backgroundScene: "None",
    LeftShadowWidth: 100,
    LeftShadowAlpha: 1,
    RightShadowWidth: 40,
    RightShadowAlpha: 0.6,
    ShowTopLeftShadow: "Yes",
    FlipStyle: "Flip",
    FlipDirection: "0",
    autoDoublePage: "Yes",
    showMirrorSide: "Show",
    SingleModeBanFlipToLastPage: "No",
    retainBookCenter: "Yes",
    isTheBookOpen: "No",
    RightToLeft: "No",
    pageBackgroundColor: "#FFFFFF",
    OriginPageIndex: 1,
    flipshortcutbutton: "Show",
    QRCode: "Hide",
    thicknessWidthType: "thick",
    thicknessColor: "#FFFFFF",
    showThicknessOnMobile: "No",
    BindingType: "side",
    HardPageEnable: "No",
    hardCoverBorderWidth: 8,
    cornerRound: 8,
    borderColor: "#FFFFFF",
    outerCoverBorder: "Yes",
    coverTexture: "none",
    HardInnerPageEnable: "No",
    showGotoButtonsAtFirst: "No",
    highDefinitionConversion: "No",
    isSingleBookFullWindowOnMobile: "No",
    totalPagesCaption: "",
    pageNumberCaption: "",
    leftMargin: 10,
    topMargin: 10,
    rightMargin: 10,
    bottomMargin: 10,
    leftMarginOnMobile: 0,
    topMarginOnMobile: 0,
    rightMarginOnMobile: 0,
    bottomMarginOnMobile: 0,
    bleedAreaLeft: "0%",
    bleedAreaTop: "0%",
    bleedAreaRight: "0%",
    bleedAreaBottom: "0%",
    maxWidthToSmallMode: "400",
    maxHeightToSmallMode: "400",
    bookTitle: "Merry Christmas Kyle",
    bookDescription: "",
    ToolBarAlpha: 1,
    toolbarColor: "#FFFFFF",
    iconColor: "#CCCCCC",
    iconFontColor: "#000000",
    pageNumColor: "#333333",
    formBackgroundColor: "#111111",
    formFontColor: "#EEEEEE",
    leftRightPnlShowOption: "none",
    appLogoIcon: "",
    appLogoLinkURL: "",
    appLogoOpenWindow: "Blank",
    logoHeight: "25",
    logoPadding: "10",
    logoTop: "8",
    FirstButtonIcon: "",
    PreviousButtonIcon: "",
    NextButtonIcon: "",
    LastButtonIcon: "",
    enablePageBack: "Hide",
    BackwardButtonIcon: "",
    ForwardButtonIcon: "",
    HomeButtonVisible: "Hide",
    HomeURL: "%first page%",
    HomeButtonIcon: "",
    AnnotationButtonVisible: "Hide",
    AnnotationButtonIcon: "",
    ShareButtonVisible: "Hide",
    ShareButtonIcon: "",
    addCurrentPage: "Hide",
    facebookShotImageURL: "",
    ThumbnailsButtonVisible: "Hide",
    ThumbnailButtonIcon: "",
    ZoomButtonVisible: "Show",
    SupportOperatePageZoom: "Yes",
    ZoomToolbarVisible: "Yes",
    ZoomMapVisible: "No",
    ZoomInButtonIcon: "",
    ZoomOutButtonIcon: "",
    MagnifierButtonVisible: "Hide",
    FullscreenButtonVisible: "Show",
    FullscreenButtonIcon: "",
    ExitFullscreenButtonIcon: "",
    hideMiniFullscreen: "No",
    BookMarkButtonVisible: "Hide",
    BookmarkButtonIcon: "",
    TableOfContentButtonVisible: "Hide",
    isHideTabelOfContentNodes: "Yes",
    TableOfContentButtonIcon: "",
    SearchButtonVisible: "Hide",
    leastSearchChar: 3,
    searchKeywordFontColor: "#FFB000",
    searchHightlightColor: "#FDC606",
    SearchButtonIcon: "",
    SelectTextButtonVisible: "Hide",
    SelectTextButtonIcon: "",
    PrintButtonVisible: "Hide",
    PrintButtonIcon: "",
    printWatermarkFile: "",
    FlipSound: "Yes",
    BackgroundSoundButtonVisible: "Hide",
    BackgroundSoundURL: "",
    BackgroundSoundLoop: -1,
    BackgroundSoundButtonOnIcon: "",
    BackgroundSoundButtonOffIcon: "",
    HelpButtonVisible: "Hide",
    helpContentFileURL: "",
    helpWidth: 400,
    helpHeight: 450,
    showHelpContentAtFirst: "No",
    HelpButtonIcon: "",
    InstructionsButtonVisible: "Hide",
    showBookInstructionOnStart: "No",
    showInstructionOnStart: "No",
    aboutButtonVisible: "Hide",
    CompanyLogoFile: "",
    AboutButtonIcon: "",
    AutoPlayButtonVisible: "Hide",
    autoPlayAutoStart: "No",
    autoPlayDuration: 5,
    autoPlayLoopCount: 1,
    AutoPlayStartButtonIcon: "",
    AutoPlayStopButtonIcon: "",
    minZoomWidth: 403,
    minZoomHeight: 518,
    DownloadButtonVisible: "Hide",
    DownloadButtonIcon: "",
    DownloadURL: "",
    VideoButtonVisible: "Hide",
    VideoButtonIcon: "",
    SlideshowButtonVisible: "Hide",
    SlideshowButtonIcon: "",
    PhoneButtonVisible: "Hide",
    PhoneButtonIcon: "",
    flippingTime: 0.5,
    mouseWheelFlip: "Yes",
    CurlingPageCorner: "Yes",
    updateURLForPage: "Yes",
    updatePageNumberForFlip: "No",
    isStopMouseMenu: "Yes",
    haveAdSense: "No",
    adSenseWidth: 200,
    adSenseHeight: 200,
    adSenseLeft: 50,
    adSenseTop: 50,
    adSenseClientId: "",
    googleAnalyticsID: "",
    language: "English",
    AboutAddress: "",
    AboutEmail: "",
    AboutMobile: "",
    AboutWebsite: "",
    AboutDescription: "",
    AboutAuthor: "",
    SlideshowAutoPlay: false,
    SlideshowPlayInterval: 5,
    totalPageCount: 10,
    largePageWidth: 640,
    largePageHeight: 960,
    normalPath: "img/",
    largePath: "img/",
    thumbPath: "img/",
};
var fliphtml5_pages = [
	{ l: "img/1.jpg"},
	{ l: "img/2.jpg"},
	{ l: "img/3.jpg"},
	{ l: "img/4.jpg"},
	{ l: "img/5.jpg"},
	{ l: "img/6.jpg"},
	{ l: "img/7.jpg"},
	{ l: "img/8.jpg"},
	{ l: "img/9.jpg"},
	{ l: "img/10.jpg"},
];
var language = [
    {
        language: "english",
        btnFirstPage: "First",
        btnNextPage: "Next",
        btnLastPage: "Last",
        btnPrePage: "Previous",
        btnGoToHome: "Home",
        btnDownload: "Download",
        btnSoundOn: "Sound On",
        btnSoundOff: "Sound Off",
        btnPrint: "Print",
        btnThumb: "Thumbnails",
        btnBookMark: "Bookmark",
        frmBookMark: "Bookmark",
        btnZoomIn: "Zoom In",
        btnZoomOut: "Zoom Out",
        btnAutoFlip: "Auto Flip",
        btnStopAutoFlip: "Stop Auto Flip",
        btnSocialShare: "Share",
        btnHelp: "Help",
        btnAbout: "About",
        btnSearch: "Search",
        btnFullscreen: "Fullscreen",
        btnExitFullscreen: "Exit Fullscreen",
        btnMore: "More",
        frmPrintCaption: "Print",
        frmPrintall: "Print All Pages",
        frmPrintcurrent: "Print Current Page",
        frmPrintRange: "Print Range",
        frmPrintexample: "Example: 2,3,5-10",
        frmPrintbtn: "Print",
        frmShareCaption: "Share",
        frmShareLabel: "Share",
        frmShareInfo: "You can easily share this publication to social networks.Just click the appropriate button below",
        frminsertLabel: "Insert to Site",
        frminsertInfo: "Use the code below to embed this publication to your website.",
        frmaboutcaption: "Contact",
        frmaboutcontactinformation: "Contact Information",
        frmaboutADDRESS: "Address",
        frmaboutEMAIL: "Email",
        frmaboutWEBSITE: "Website",
        frmaboutMOBILE: "Mobile",
        frmaboutAUTHOR: "Author",
        frmaboutDESCRIPTION: "Description",
        frmSearch: "Search",
        frmToc: "Table Of Contents",
        btnTableOfContent: "Table Of Contents",
        btnNote: "Annotation",
        lblLast: "This is the last page.",
        lblFirst: "This is the first page.",
        lblFullscreen: "Click to view in fullscreen",
        lblName: "Name",
        lblPassword: "Password",
        lblLogin: "Login",
        lblCancel: "Cancel",
        lblNoName: "User name can not be empty.",
        lblNoPassword: "Password can not be empty.",
        lblNoCorrectLogin: "Please enter the correct user name and password.",
        btnVideo: "Video Gallery",
        btnSlideShow: "Slideshow",
        pnlSearchInputInvalid: "The search text is too short.",
        btnDragToMove: "Move by mouse drag",
        btnPositionToMove: "Move by mouse position",
        lblHelp1: "Drag the page corner to view",
        lblHelp2: "Double click to zoom in, out",
        lblCopy: "Copy",
        lblAddToPage: "Add To Page",
        lblPage: "Page",
        lblTitle: "Title",
        lblEdit: "Edit",
        lblDelete: "Delete",
        lblRemoveAll: "Remove All",
        tltCursor: "Cursor",
        tltAddHighlight: "Add highlight",
        tltAddTexts: "Add texts",
        tltAddShapes: "Add shapes",
        tltAddNotes: "Add notes",
        tltAddImageFile: "Add image file",
        tltAddSignature: "Add signature",
        tltAddLine: "Add line",
        tltAddArrow: "Add arrow",
        tltAddRect: "Add rect",
        tltAddEllipse: "Add ellipse",
        lblDoubleClickToZoomIn: "Double click to zoom in.",
        lblPages: "Pages",
        infCopyToClipboard: "Your browser dose not support clipboard, please do it yourself.",
        lblDescription: "Title",
        frmLinkLabel: "Link",
        infNotSupportHtml5: "Your browser does not support HTML5.",
        frmHowToUse: "How To Use",
        lblHelpPage1: "Move your finger to flip the book page.",
        lblHelpPage2: "Zoom in by using gesture or double click on the page.",
        lblHelpPage3: "Click on the logo to reach the official website of the company.",
        lblHelpPage4: "Add bookmarks, use search function and auto flip the book.",
        lblHelpPage5: "Switch horizontal and vertical view on mobile devices.",
        frmQrcodeCaption: "Scan the bottom two-dimensional code to view with mobile phone.",
        btnPageBack: "Backward",
        btnPageForward: "Forward",
        btnLanguage: "Change Language",
        msgConfigMissing: "Configuration file is missing, unable to open the book.",
        btnPhoneNumber: "Tel",
        frmTelephone: "Tel",
        btnDialing: "Call",
        lblSelectMessage: "Please copy the the text content in the text box.",
        btnSelectText: "Select Text",
        DownloadCurrentPage: "Include Current Page",
        restorePage: "Would you like to restore previous session",
        lblSave: "Save",
    },
];
var ols = [];
var bmtConfig = { tabs: [], onSideEdge: true };
var staticAd = { haveAd: false, interval: 3000, data: [] };
var videoList = [];
var slideshow = [];
var flipByAudio = { audioType: 0, audioFile: "", showPlayer: false, items: [] };
var phoneNumber = [];
var bookPlugin = null;
